###
GET http://localhost:4000/api/employees

###
POST  http://localhost:4000/api/employees
Content-Type: application/json

{
    "name": "Alejandro Rojas",
    "position": "Junior Developer",
    "office": "Dev",
    "salary": 5000000
}

###
GET http://localhost:4000/api/employees/607e32f1b482452522f39f11

###
DELETE http://localhost:4000/api/employees/607e32f1b482452522f39f11

###
PUT http://localhost:4000/api/employees/607e32f1b482452522f39f11
Content-Type: application/json

{
    "name": "Marlon Lopez",
    "position": "SEO AND SEN",
    "office": "Marketing Digital",
    "salary": 9000000
}

